### ISSUE TITLE
Contact and Follow Don't Link

### ISSUE THREAD

**Issue by yrrapt** [mosaic-ic/mosaic-ic.github.io#14]
The 'contact' and 'follow' text at the bottom of the page currently don't link anywhere.

At the moment there's no way for someone to contact the group so it would be great to add the ability for people to get in touch.

**Comment by curtisma** [comment]
Updated:
![image](https://user-images.githubusercontent.com/4685385/194208147-b8764e9a-fd5d-443d-865e-e8d9df1729bd.png)
